video_player_right:
  ros__parameters:
    # specify the video file path for right camera here
    video_path: '/home/amatrix/Userfiles/Robomaster/hfut_rm_auto_aim_ws/test_video/output.avi'
    loop_playback: true
    fps: 30.0
    camera_name: 'video_camera_right'
    frame_id: 'video_camera_right_optical_frame'
    flip_image: false
    image_topic: 'image_raw_right'
    use_sensor_data_qos: false
    # camera_info_manager YAML for right camera
    camera_info_url: 'package://video_player/config/dual_01/camera_info_right.yaml'
